### ISSUE TITLE
Usage of Dagger 2 with flow and mortar

### ISSUE THREAD

**Issue by scana** [pyricau/dagger2-mortar-flow-experiment#2]
Hi Pierre, I've attented your speech at MCE in Warsaw (it was really great btw, thx!).
The problem is that I forgot to ask one question which is really important for me. Does Mortar+Flow setup works out of a box with Dagger 2 nowadays or does it requires to include some stuff from Dagger 1?
MCE is still taking place, so I probably will try to find you, but, just in case, I'm gonna post my question here.

**Comment by pyricau** [comment]
This was an experiment that I made 6 months ago.

Mortar & Flow aren't specific to Dagger1, not even specific to Dagger. So yeah, it works out of the box with Dagger 2 as well.
